name: 'ORYX QMK Firmware Compiler Action (zsa only)'
author: 'Phoscur'
description: 'Compiles QMK Firmware from ORYX source'
branding:
  icon: 'settings'  
  color: 'orange'
inputs:
  layout_id:
    description: 'ORYX layout hash ID'
    required: true
  path:
    description: 'Path to keymap source folder'
    default: '.'
  artifacts_path:
    description: 'Path to output build results'
    default: 'artifacts'
  keymap:
    description: 'Keymap name'
    default: 'neo'
  keyboard:
    description: 'Keyboard type'
    default: 'moonlander'
  fork:
    description: 'Fork of QMK on Github'
    default: 'zsa/qmk_firmware'
  branch:
    description: 'Branch of fork. Uses default branch when empty'
runs:
  using: "composite"
  steps:
    - name: Checkout the commit
      uses: actions/checkout@v2

    - name: Build QMK container
      run: docker compose build
      shell: bash
      env:
        FORK: ${{ inputs.fork }}
        BRANCH: ${{ inputs.branch }}

    - name: Compile Keyboard
      run: docker compose run qmk
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_ARTIFACTS_PATH: ${{ inputs.artifacts_path }}
        INPUT_KEYMAP: ${{ inputs.keymap }}
        INPUT_KEYBOARD: ${{ inputs.keyboard }}